"""Add location fields to User table

Revision ID: 8cbfad4b7d25
Revises: 3d4c050dedac
Create Date: 2024-10-15 21:01:12.403962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbfad4b7d25'
down_revision = '3d4c050dedac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_location_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_location_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('live_location_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('live_location_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('live_location_longitude')
        batch_op.drop_column('live_location_latitude')
        batch_op.drop_column('current_location_longitude')
        batch_op.drop_column('current_location_latitude')

    # ### end Alembic commands ###
